# taskfile-go
version: 3

vars:
  title_json: build/title.json
  title_hex: build/title.hex
  bin_file: build/title.uiff

tasks:
  data_mk:
    desc: yamlをuiffに変換する
    cmds:
      - mkdir -p build
      - yq -o json assets/title.yaml > {{.title_json}}
      - python compiler/uiff_conv_test.py {{.title_json}} -def assets/defines.json > {{.title_hex}}
      - cat {{.title_hex}} | xxd -r -p > {{.bin_file}}

  data_hex:
    desc: yamlをuiffの16進数で出力する
    cmds:
      - yq -o json assets/title.yaml > {{.title_json}}
      - python compiler/uiff_conv_test.py {{.title_json}} -def assets/defines.json

  data_ck:
    desc: uiffを確認する
    cmds:
      - python compiler/uiff_check.py {{.bin_file}}

  run:
    desc: uiffを実行する
    cmds:
      - swift run --package-path swiftUI

  build:
    desc: uiffをビルドする
    cmds:
      - swift build --package-path swiftUI

  clean:
    desc: clean up generated files
    cmds:
      - rm -f {{.title_json}} {{.bin_file}} {{.title_hex}}

  default:
    cmds:
      - task --list

