# taskfile-go
version: 3

vars:
  title_json: assets/title.json
  bin_file: assets/title.uiff

tasks:
  run:
    desc: uiffをコンパイルして結果を確認する
    cmds:
      - python compiler/uiff_conv.py {{.title_json}} -def assets/defines.json

  bin:
    desc: yamlをuiffに変換する
    cmds:
      - yq -o json assets/title.yaml > {{.title_json}}
      - set -o pipefail; python compiler/uiff_conv.py {{.title_json}} -def assets/defines.json | xxd -r -p > {{.bin_file}}

  check:
    desc: uiffを確認する
    cmds:
      - python compiler/uiff_check.py {{.bin_file}}

  default:
    cmds:
      - task --list

