// Error定数
private let UIFF_ERR_BASE = 0x3000_0000

// UIFFファイル関連のエラーコード
public let UIFF_ERR_FILE_INVALID = UIFF_ERR_BASE | 0x1
public let UIFF_ERR_FILE_TOO_LARGE = UIFF_ERR_BASE | 0x2
public let UIFF_ERR_CHUNK_INVALID = UIFF_ERR_BASE | 0x3

// Event関連のエラーコード
private let UIFF_ERR_EVENT_BASE = UIFF_ERR_BASE | 0x0100_0000
public let UIFF_ERR_EVENT_INVALID = UIFF_ERR_EVENT_BASE | 0x1
